paths:
  /api/products:
    get: 
      summary: Get all products
      tags:
        - Products
      responses: 
        "200": 
          description: All products
          # content:
          #   application/json:
          #     schemas:
          #       type: Array
          #       items:
          #         $ref: '#/components/shemas/Product'
        "500":
          description: Server error
        "400":
          description: Missing data

  /api/products/{idProduct}:
    get: 
      summary: Get one products
      tags:
        - Products
      parameters:
        - name: idProduct
          in: path
          description: Product identifier
      responses: 
        "200": 
          description: One products
          content:
            application/json:
              schemas:
                  # $ref: '#/components/schemas/productos'
              example:
                id: ljs948sp
                title: control
                description: control para TV
                code: jslj9499
                precio: 900
                status: true
                stock: 3
                category: Electronica
                thumnails: pag web de la img
        "500":
          description: Server error
        "400":
          description: Missing data
  #Products
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        code:
          type: string
        precio:
          type: number
        status:
          type: boolean
        stock:
          type: number
        category:
          type: string
        thumbanils:
          type: string
        example:
          id: ljs948sp
          title: control
          description: control para TV
          code: jslj9499
          precio: 900
          status: true
          stock: 3
          category: Electronica
          thumnails: pag web de la img
